name = "cuidandote-admin-login-proxy"
main = "src/index.js"
compatibility_date = "2026-08-03"

[assets]
directory = "../admin"
binding = "ASSETS"

[[routes]]
pattern = "login-pruebas.cuidandotefisioterapia.com"
custom_domain = true
